{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9cb21659-8ebb-4610-9d8e-868932405f1c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-25 21:46:29.311 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.312 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.862 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-25 21:46:29.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.864 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.882 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.897 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-25 21:46:29.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.929 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.932 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.946 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.953 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:29.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-25 21:46:30.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from datetime import date\n",
    "\n",
    "# -------- FILE SETUP --------\n",
    "DATA_FILE = Path(\"athletes_data.csv\")\n",
    "\n",
    "# Function to load data\n",
    "def load_data():\n",
    "    if DATA_FILE.exists():\n",
    "        return pd.read_csv(DATA_FILE)\n",
    "    else:\n",
    "        return pd.DataFrame(columns=[\n",
    "            \"Athlete Name\", \"Club\", \"Nationality\", \"Date of Birth\", \"Sex\", \"Player Code\",\n",
    "            \"Belt Degree\", \"Competitions\"\n",
    "        ])\n",
    "\n",
    "# Function to save data\n",
    "def save_data(df):\n",
    "    df.to_csv(DATA_FILE, index=False)\n",
    "\n",
    "# -------- STREAMLIT UI --------\n",
    "st.set_page_config(page_title=\"Championship Registration Form\")\n",
    "st.title(\"🏆 Championship Registration Form\")\n",
    "\n",
    "# -------- PAGE 1 — ADD ATHLETE --------\n",
    "st.header(\"Add New Athlete\")\n",
    "\n",
    "with st.form(\"reg_form\"):\n",
    "    athlete_name = st.text_input(\"Athlete Name\")\n",
    "    club = st.text_input(\"Club\")\n",
    "    nationality = st.text_input(\"Nationality\")\n",
    "    dob = st.date_input(\n",
    "        \"Date of Birth\",\n",
    "        min_value=date(1960,1,1),\n",
    "        max_value=date.today()\n",
    "    )\n",
    "    sex = st.selectbox(\"Sex\", [\"Male\", \"Female\"])\n",
    "    player_code = st.text_input(\"Player Code\")\n",
    "    belt_degree = st.text_input(\"Belt Degree\")\n",
    "\n",
    "    competitions_list = [\n",
    "        \"Individual Kata\",\n",
    "        \"Kata Team\",\n",
    "        \"Individual Kumite\",\n",
    "        \"Fuko Go\",\n",
    "        \"Inbo Mix\",\n",
    "        \"Inbo Male\",\n",
    "        \"Inbo Female\",\n",
    "        \"Kumite Team\"\n",
    "    ]\n",
    "\n",
    "    competitions = st.multiselect(\"Choose Competitions\", competitions_list)\n",
    "    submitted = st.form_submit_button(\"Submit\")\n",
    "\n",
    "if submitted:\n",
    "    df = load_data()\n",
    "\n",
    "    if player_code in df[\"Player Code\"].values:\n",
    "        st.error(\"Player Code already exists!\")\n",
    "    else:\n",
    "        new_row = {\n",
    "            \"Athlete Name\": athlete_name,\n",
    "            \"Club\": club,\n",
    "            \"Nationality\": nationality,\n",
    "            \"Date of Birth\": dob,\n",
    "            \"Sex\": sex,\n",
    "            \"Player Code\": player_code,\n",
    "            \"Belt Degree\": belt_degree,\n",
    "            \"Competitions\": \", \".join(competitions)\n",
    "        }\n",
    "\n",
    "        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)\n",
    "        save_data(df)\n",
    "        st.success(\"Athlete registered successfully! 🎉\")\n",
    "\n",
    "# -------- ADMIN LOGIN --------\n",
    "st.sidebar.header(\"Admin Login\")\n",
    "admin_password = st.sidebar.text_input(\"Enter Admin Password\", type=\"password\")\n",
    "\n",
    "if admin_password == \"mobadr90\": \n",
    "    st.sidebar.success(\"Logged in as Admin ✅\")\n",
    "    st.header(\"Admin Panel\")\n",
    "    df = load_data()\n",
    "    if df.empty:\n",
    "        st.info(\"No data found yet.\")\n",
    "    else:\n",
    "        st.dataframe(df, use_container_width=True)\n",
    "\n",
    "        # Download Excel\n",
    "        st.download_button(\n",
    "            label=\"📥 Download Excel\",\n",
    "            data=df.to_excel(index=False, engine='openpyxl'),\n",
    "            file_name=\"athletes_data.xlsx\",\n",
    "            mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"\n",
    "        )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "b1b069f4-4aeb-473c-b22e-d3848692621a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
